# Generated by Django 5.2.9 on 2025-12-16 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_options_alter_bookinstance_id_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=10000),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43141031-8fbe-4684-bd0b-738a0f529beb'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
